# applicationName: "deployment-test"
application:
  name: "deployment-test"
  product: gnog
  team: infra-and-ops
  env: dev

image:
  repository: nginxdemos/hello
  tag: stable
  pullPolicy: Always

ports:
  - name: http
    port: 80
    protocol: TCP

probe:
  httpGet:
    path: /
    port: 80