name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    needs: test-job
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - name: Tag using semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm i @semantic-release/exec -D
          npx semantic-release@beta
  publish-docker-image:
    runs-on: ubuntu-latest
    name: Publish docker image
    needs: tag
    if: github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_KEY }}
    - run: gcloud auth configure-docker
    - name: push to gcr and github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_IMAGE_GITHUB: docker.pkg.github.com/g-loot/action-deploy-helm/deploy-helm
        DOCKER_IMAGE_GCR: gcr.io/gloot-automation/action-deploy-helm
      run: |
        export VERSION=$(git describe --tags)
        docker login docker.pkg.github.com -u g-loot -p $GITHUB_TOKEN
        docker build . -t $DOCKER_IMAGE_GITHUB:latest -t $DOCKER_IMAGE_GITHUB:$VERSION \
          -t $DOCKER_IMAGE_GCR:latest -t $DOCKER_IMAGE_GCR:$VERSION
        docker push $DOCKER_IMAGE_GITHUB:latest
        docker push $DOCKER_IMAGE_GCR:latest
        docker push $DOCKER_IMAGE_GITHUB:$VERSION
        docker push $DOCKER_IMAGE_GCR:$VERSION
  test-job:
    runs-on: ubuntu-latest
    name: Test deployment
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use local Dockerfile
        run: |
          sed -i 's^docker://gcr.io/gloot-automation/action-deploy-helm:latest^Dockerfile^g' action.yml
      - name: Deploy test application
        uses: ./
        with:
          gcp_key: ${{ secrets.GCP_KEY }}
          application_name: test-deploy
          helm_args: "-f values.yaml --set image.tag=latest"
      - name: Purge test application
        uses: ./
        with:
          gcp_key: ${{ secrets.GCP_KEY }}
          application_name: test-deploy
          helm_args: "-f values.yaml --set image.tag=latest"
          helm_command: "delete --purge $RELEASE_NAME"
  lint-commit:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - run: |
          npm i @commitlint/{config-angular,cli} -D
          npx commitlint -x "@commitlint/config-angular" --from=origin/master --to=HEAD
