name: CI-Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tag:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v1
      - name: Bump version and push tag
        id: version_bump
        uses: anothrNick/github-tag-action@1.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: "patch"
          RELEASE_BRANCHES: "master"
  publish-docker-image:
    runs-on: ubuntu-latest
    name: Publish docker image
    needs: tag
    if: github.event_name == 'push'
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_KEY }}
    - run: gcloud auth configure-docker
    - name: push to gcr and github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_IMAGE_GITHUB: docker.pkg.github.com/g-loot/action-deploy-helm/deploy-helm
        DOCKER_IMAGE_GCR: gcr.io/gloot-automation/action-deploy-helm
      run: |
        export VERSION=$(git describe --tags)
        docker login docker.pkg.github.com -u g-loot -p $GITHUB_TOKEN
        docker build . -t $DOCKER_IMAGE_GITHUB:latest -t $DOCKER_IMAGE_GITHUB:$VERSION \
          -t $DOCKER_IMAGE_GCR:latest -t $DOCKER_IMAGE_GCR:$VERSION
        docker push $DOCKER_IMAGE_GITHUB:latest
        docker push $DOCKER_IMAGE_GCR:latest
        docker push $DOCKER_IMAGE_GITHUB:$VERSION
        docker push $DOCKER_IMAGE_GCR:$VERSION