name: CI-Deploy

on:
  push:
    branches:
      - master

jobs:
  build-publish-docker-image:
    runs-on: ubuntu-latest
    name: Publish docker image
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup GCP
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.0'
        service_account_email: ${{ secrets.GCP_EMAIL }}
        service_account_key: ${{ secrets.GCP_KEY }}
    - run: gcloud auth configure-docker
    - name: Bump version and push tag
      id: version_bump
      uses: anothrNick/github-tag-action@1.8.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DEFAULT_BUMP: "patch"
        RELEASE_BRANCHES: "master"
    - name: push to gcr and github
      env:
        DOCKER_IMAGE_GCR: gcr.io/gloot-automation/action-deploy-helm
      run: |
        docker build . -t $DOCKER_IMAGE_GCR:latest -t $DOCKER_IMAGE_GCR:${{ steps.version_bump.outputs.tag }}
